### ISSUE TITLE
iOS Mediation Support for AdMob

### ISSUE THREAD

**Issue by SimoneAtDoveConviene** [pubnative/pubnative-ios-sdk#1]
Reading PubNative website and browsing the code tree I couldn't find any support for AdMob Network mediation which Android has.
It could be nice to have support for it in iOS too.
Did you already planned to support AdMob mediation for iOS in the near future?
Thanks a lot.

**Comment by dvmrmc** [comment]
Hello @SimoneAtDoveConviene sorry for the delay on this, yeah we have planned support for AdMob network in an upcoming version, I'll keep you updated with this, thanks
