### ISSUE TITLE
Language Clarification ( Swift or C++ )

### ISSUE THREAD

**Issue by vrySantosh** [pubnative/pubnative-ios-sdk#2]
Hi,

I'm Santosh. I have been looking at your code, I can see this was written in swift. But, I want to clarify with you guys about below  picture. 
<img width="832" alt="screen shot 2016-11-25 at 3 07 35 pm" src="https://cloud.githubusercontent.com/assets/7948604/20617219/a1aae222-b322-11e6-9c89-ad0125473c34.png">

& 

I have been running in xcode 8 and updated to swift 3, its been striking at many classes. If its okay to update then please do it.

A million thanks !!

**Comment by dvmrmc** [comment]
Hello @elSantosh Yeah It should be safe to upgrade since the library itself is written in ObjC.

The Swift code is corresponding to the demo app and the C++ code is corresponding to OCLint (a lint tool for ObjC for improving code incremental development).

Feel free to update 👍
