### ISSUE TITLE
Adapters not working

### ISSUE THREAD

**Issue by neobeppe** [pubnative/pubnative-ios-sdk#5]
Hi, adapters are broken in 2.0.0 and 2.0.1

You can find a fix here: [https://github.com/neobeppe/pubnative-ios-sdk](https://github.com/neobeppe/pubnative-ios-sdk)

You have a PR with the fixes.

**Comment by can-soykarafakili** [comment]
Hi @neobeppe,

Thank you for your suggestions & fixes. We are going review them and release a new version soon.

Have a good day.
